### ISSUE TITLE
ResolvePackageNotFound

### ISSUE THREAD

**Issue by LovelyBuggies** [Xingyu-Lin/softagent#2]
Dear,

When I was creating softagent conda env, it threw an error:

```
ResolvePackageNotFound: 
  - dm-env
  - imageio-ffmpeg
  - moviepy
  - opencv-python=5.1.1
  - torch=1.7.1
  - gtimer
  - sk-video
  - gym=0.14.0
  - //github.com/1nadequacy/dmc2gym.git
  - pyquaternion=0.9.5
  - dm-tree
```

I tried to create a new env, doesn't work either. I assumed it would be risky to pip intall them in the conda env one-by-one.

**Comment by Xingyu-Lin** [comment]
Actually I think these packages should be fine with a pip install. I have updated this.

**Comment by LovelyBuggies** [comment]
I have another try with your new environment.yml. The error still exists.
