### ISSUE TITLE
Issue with self.action_repeat in softagent/envs/env.py

### ISSUE THREAD

**Issue by rehaanahmad2013** [Xingyu-Lin/softagent#3]
I have a question regarding the usage of action_repeat in the 'step' function in softagent/envs/env.py. I see that it has "self._env.step()" inside the for loop repeating 8 times (self.action_repeat):
![image](https://user-images.githubusercontent.com/34905129/125146634-9fe55a80-e0db-11eb-93da-1598dd112e18.png)
However, when I looked at the self._env.step() function which is in "softgym/flex_env.py", it also has a for loop that runs "self.action_repeat" steps of the environment here:
![image](https://user-images.githubusercontent.com/34905129/125146603-788e8d80-e0db-11eb-9c21-271481ae664d.png)

Doesn't this mean that for one call of 'step' in SoftAgent, we are actually executing pyflex.step() 64 times? Is this intended (or perhaps I'm missing something here)? If so, could we just remove the for loop inside the SoftAgent env and set self.action_repeat to 64?

**Comment by Xingyu-Lin** [comment]
Yes, this is indeed confusing. Only the action_repeat in flex_env.py is used and set to either 8 or 16. The action_repeat in softagent's env.py is set to 1 and thus does not affect the total repeats
